data:
  descriptor_cache_csv: resources/descriptors/hmdb_physchem.csv
  random_seed: 42

tasks:
  use_logp: true
  use_molvol: true

loss:
  lambda_similarity: 1.0

  lambda_logp_abs: 0.20
  lambda_logp_delta: 0.1

  lambda_molvol_abs: 0.3
  lambda_molvol_delta: 0.1

training:
  results_name: Siamese_physchem_wide_only_test
  batch_size: 64
  max_epochs: 2000
  early_stopping_patience: 10
  early_stopping_min_delta: 0.000002
  reduce_lr_patience: 4
  reduce_lr_factor: 0.3333333
